describe usuarios;
select * from usuarios;

insert into usuarios (nome_usuario, username_usuario, email_usuario, senha_usuario)
values ('João', 'joãoSilva99','joao@gmail','joao123'),
('Maria', 'mariaSouza85','maria@gmail','maria123'),
('Pedro', 'pedroFerreira77','pedro@gmail','pedro123'),
('Ana', 'anaOliveira64','ana@gmail','ana123'),
('Lucas', 'lucasSantos52','lucas@gmail','lucas123'),
('Carolina', 'carolinaRocha42','carolina@gmail','carolina123'),
('Marcos', 'marquinhos02','marcos@gmail','marcos123'),
('Juliana', 'jujulima28','juliana@gmail','juliana123'),
('Rafael', 'rafinha00','rafael@gmail','rafael123'),
('Fernanda', 'fegomes19','fernanda@gmail','fernanda123'),
('Guilherme', 'guilhermeCosta16','guilherme@gmail','guilherme123'),
('André', 'andre2244','andre@gmail','andre123'),
('Beatriz', 'beatrizCav2','beatriz@gmail','beatriz123'),
('Tiago', 'thithi27','thiago@gmail','thiago123'),
('Mariana', 'maryy32','mariana@gmail','mariana123'),
('Carlos', 'carlitos03','carlos@gmail','carlos123'),
('Gabriela', 'gabilopez','gabriela@gmail','gabriela123'),
('Eduarda', 'dudinha78','eduarda@gmail','eduarda123'),
('Amanda', 'amandinha333','amanda@gmail','amanda123'),
('Luiz', 'LuizGon1','luiz@gmail','luiz123'),
('Isabella', 'bellinha3','isabella@gmail','isabella123'),
('Rodrigo', 'rodriguinho07','rodrigo@gmail','rodrigo123'),
('Patrícia', 'patty97','patricia@gmail','patricia123'),
('Leonardo', 'LeozinhoS','leonardo@gmail','leonardo123'),
('Renata', 'renatinha23','renata@gmail','renata123'),
('Marcelo', 'marcelo30','marcelo@gmail','marcelo123'),
('Vanessa', 'vanessinha22','vanessa@gmail','vanessa123'),
('Rafaella', 'rafa222','rafaella@gmail','rafaella123'),
('Danilo', 'danilo43','danilo@gmail','danilo123'),
('Jurema', 'jureminha','jurema@gmail','jurema123'),
('Gustavo', 'guguinha21','gustavo@gmail','gustavo123'),
('Bruno', 'bruninhoMars','bruno@gmail','bruno123');